/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frontent.Reporte;

import Backend.Reporte.ControladorReportes;
import Exceptions.AccesoALaDataException;
import Exceptions.CreacionArchivoException;
import Exceptions.ErrorIngresarDatosException;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class VentanaReporte extends javax.swing.JInternalFrame {
    
    private ControladorReportes controladorReportes;
    
    public VentanaReporte() {
        initComponents();
    }
    
    public void setControladorReportes(ControladorReportes controladorReportes) {
        this.controladorReportes = controladorReportes;
    }

    public String getAñoFinal() {
        return añoFinal.getText();
    }

    public String getAñoInicial() {
        return añoInicial.getText();
    }

    public String getDiaFinal() {
        return diaFinal.getText();
    }

    public String getDiaInicial() {
        return diaInicial.getText();
    }

    public String getMesFinal() {
        return mesFinal.getText();
    }

    public String getMesInicial() {
        return mesInicial.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        informacionGastos = new javax.swing.JLabel();
        diaInicial = new javax.swing.JTextField();
        mesInicial = new javax.swing.JTextField();
        añoInicial = new javax.swing.JTextField();
        diaFinal = new javax.swing.JTextField();
        mesFinal = new javax.swing.JTextField();
        añoFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        espacioInsumos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        espacioRanking = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        informacionVentas = new javax.swing.JLabel();
        informacionGanancias = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel1.setText("Reportes de JavaBeans Cafe");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel2.setText("Flujo de Caja");

        informacionGastos.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        informacionGastos.setText("Gasto: 000");

        diaInicial.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        mesInicial.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        añoInicial.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        diaFinal.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        mesFinal.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        añoFinal.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel4.setText("Dia   Mes Año");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel5.setText("Dia   Mes  Año");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel6.setText("Buscar el flujo de Caja entre las fechas");

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jButton2.setText("Exportar Reporte");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel7.setText("Productos en limite de Stock");

        javax.swing.GroupLayout espacioInsumosLayout = new javax.swing.GroupLayout(espacioInsumos);
        espacioInsumos.setLayout(espacioInsumosLayout);
        espacioInsumosLayout.setHorizontalGroup(
            espacioInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        espacioInsumosLayout.setVerticalGroup(
            espacioInsumosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(espacioInsumos);

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel8.setText("Ranking de Productos");

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jButton3.setText("Exportar Reporte");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout espacioRankingLayout = new javax.swing.GroupLayout(espacioRanking);
        espacioRanking.setLayout(espacioRankingLayout);
        espacioRankingLayout.setHorizontalGroup(
            espacioRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        espacioRankingLayout.setVerticalGroup(
            espacioRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(espacioRanking);

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jButton4.setText("Exportar Reporte");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        informacionVentas.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        informacionVentas.setText("Ventas: 000");

        informacionGanancias.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        informacionGanancias.setText("Ganancia: 000");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel9.setText("Fecha Inicial");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel10.setText("Fecha Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informacionGastos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(diaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(añoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(diaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(añoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(14, 14, 14))
                            .addComponent(informacionVentas)
                            .addComponent(informacionGanancias)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel9)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton2)))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(139, 139, 139))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(386, 386, 386))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacionGanancias)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controladorReportes.pedirReportesFechas();
        } catch (AccesoALaDataException | ErrorIngresarDatosException e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            controladorReportes.exportarReporteCaja();
        } catch (AccesoALaDataException | CreacionArchivoException | ErrorIngresarDatosException e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            controladorReportes.exportarReporteRanking();
        } catch (CreacionArchivoException e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            controladorReportes.exportarReporteInsumos();
        } catch (CreacionArchivoException e) {
            mostrarMensaje(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añoFinal;
    private javax.swing.JTextField añoInicial;
    private javax.swing.JTextField diaFinal;
    private javax.swing.JTextField diaInicial;
    private javax.swing.JPanel espacioInsumos;
    private javax.swing.JPanel espacioRanking;
    private javax.swing.JLabel informacionGanancias;
    private javax.swing.JLabel informacionGastos;
    private javax.swing.JLabel informacionVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mesFinal;
    private javax.swing.JTextField mesInicial;
    // End of variables declaration//GEN-END:variables
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void setInformacionCaja(String gastos, double ventas, String ganancias) {
        informacionGastos.setText("Gastos: " + gastos);
        informacionVentas.setText("Ventas: " + ventas);
        informacionGanancias.setText("Ganancias: " + ganancias);
    }
    
    public void setFilasRanking(int filas) {
        espacioRanking.removeAll();
        espacioRanking.setLayout(new GridLayout(filas*3, 1, 5, 5));
    }
    
    public void agregarProductoRanking(int vecesVendida, String producto, int codigo) {
        JLabel jlabel = new JLabel(" Producto: " + producto);
        jlabel.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        JLabel jlabel2 = new JLabel(" Veces Vendida: " + vecesVendida + " | Codigo del Producto: " + codigo);
        jlabel2.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        JLabel espacio = new JLabel();
        espacio.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        espacioRanking.add(jlabel);
        espacioRanking.add(jlabel2);
        espacioRanking.add(espacio);
        espacioRanking.revalidate();
        espacioRanking.repaint();
    }
    
    public void setFilasProducto(int filas) {
        espacioInsumos.setLayout(new GridLayout(filas, 1, 5, 5));
    }
    
    public void limpiarProducto() {
        espacioInsumos.removeAll();
    }
    
    public void agregarProducto(String producto, double cantidadStock, String unidadMedida, double minimo) {
        JLabel jlabel = new JLabel(producto + " x " + cantidadStock + unidadMedida + " | Minimo: " + minimo + unidadMedida);
        jlabel.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        espacioInsumos.add(jlabel);
        actualizarPanelStock();
    }
    
    private void actualizarPanelStock() {
        espacioInsumos.revalidate();
        espacioInsumos.repaint();
    }
    
    public void agregarInfoProducto(String informacion) {
        limpiarProducto();
        setFilasProducto(1);
        JLabel jlabel = new JLabel(informacion);
        jlabel.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        espacioInsumos.add(jlabel);
        actualizarPanelStock();
    }
    
}
