/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontent;

import Backend.Administrador.ControlParaEmpleado;
import Frontent.Administrador.ServicioAdminstrarInsumos;
import Backend.Inventario.ControladorInventario;
import Frontent.Mesero.ServicioMesero;
import Frontent.Mesero.SubMenuMeseros;
import Frontent.Mesero.ServicioPagoCuenta;
import Frontent.Mesero.ServicioDeOrden;
import Backend.Mesero.ControladorMesero;
import Backend.Reporte.ControladorReportes;
import Exceptions.AccesoALaDataException;
import Frontent.Administrador.ServDeshabilitarEmpleado;
import Frontent.Administrador.ServicioPagoEmpleado;
import Frontent.Reporte.VentanaReporte;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class JavaBeansCafe extends javax.swing.JFrame {
    
    private final MenuProducto menu;
    private ServicioMesero servicioMesero;
    private ControladorMesero controladorMesero;
    private SubMenuMeseros subMenu;
    private ServicioDeOrden servicioOrden;
    private ServicioPagoCuenta servicioCuenta;
    private ServicioInventario servicioInventario;
    private ControladorInventario controladorInventario;
    private ServicioAdminstrarInsumos servAdministarInsumos;
    private ServicioPagoEmpleado servicioPagoEmpleado;
    private ServDeshabilitarEmpleado servDeshabilitarEmpleado;
    private ControlParaEmpleado controlParaEmpleado;
    private ControladorReportes controladorReporte;
    private VentanaReporte ventanaReporte;
    
    public JavaBeansCafe(MenuProducto menuProductos) {
        initComponents();
        this.menu = menuProductos;
        jDesktopPane1.add(menu);
        ocultarSubMenus();
    }
    
    public void setServicioMesero(ServicioMesero servicioMesero, ControladorMesero controladorMesero) {
        this.servicioMesero = servicioMesero;
        jDesktopPane1.add(servicioMesero);
        this.controladorMesero = controladorMesero;
    }
    
    public void setSubMenu(SubMenuMeseros subMenu) {
        this.subMenu = subMenu;
        jDesktopPane1.add(subMenu);
    }
    public void setServicioOrden(ServicioDeOrden servicioOrden) {
        this.servicioOrden = servicioOrden;
        jDesktopPane1.add(servicioOrden);
    }
    
    public void setServicioCuenta(ServicioPagoCuenta servicioCuenta) {
        this.servicioCuenta = servicioCuenta;
        jDesktopPane1.add(servicioCuenta);
    }

    public void setServicioInventario(ServicioInventario servicioInventario, ControladorInventario controladorInventario) {
        this.servicioInventario = servicioInventario;
        jDesktopPane1.add(servicioInventario);
        this.controladorInventario = controladorInventario;
    }

    public void setServAdministarInsumos(ServicioAdminstrarInsumos servAdministarInsumos) {
        this.servAdministarInsumos = servAdministarInsumos;
        jDesktopPane1.add(servAdministarInsumos);
    }

    public void setServicioPagoEmpleado(ServicioPagoEmpleado servicioPagoEmpleado) {
        this.servicioPagoEmpleado = servicioPagoEmpleado;
        jDesktopPane1.add(servicioPagoEmpleado);
    }

    public void setServDeshabilitarEmpleado(ServDeshabilitarEmpleado servDeshabilitarEmpleado, ControlParaEmpleado controlParaEmpleado) {
        this.servDeshabilitarEmpleado = servDeshabilitarEmpleado;
        jDesktopPane1.add(servDeshabilitarEmpleado);
        this.controlParaEmpleado = controlParaEmpleado;
    }

    public void setControladorReporte(ControladorReportes controladorReporte, VentanaReporte ventanaReporte) {
        this.controladorReporte = controladorReporte;
        this.ventanaReporte = ventanaReporte;
        jDesktopPane1.add(ventanaReporte);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();
        botonServicioMesero = new javax.swing.JButton();
        botonInventario = new javax.swing.JButton();
        botonAdministrador = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        subMenuMesero = new javax.swing.JPanel();
        botonSubMenuMeseros = new javax.swing.JButton();
        subMenuAdministrador = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jLabel1.setText("JavaBeans Cafe");

        botonMenu.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonMenu.setText("Menu");
        botonMenu.addActionListener(this::botonMenuActionPerformed);

        botonServicioMesero.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonServicioMesero.setText("Servicio de Mesero");
        botonServicioMesero.addActionListener(this::botonServicioMeseroActionPerformed);

        botonInventario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonInventario.setText("Inventario");
        botonInventario.addActionListener(this::botonInventarioActionPerformed);

        botonAdministrador.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonAdministrador.setText("Servicio de Adminstrador");
        botonAdministrador.addActionListener(this::botonAdministradorActionPerformed);

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton3.setText("Reportes");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonServicioMesero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonInventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenu)
                    .addComponent(botonServicioMesero)
                    .addComponent(botonInventario)
                    .addComponent(botonAdministrador)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        botonSubMenuMeseros.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonSubMenuMeseros.setText("Elegir Mesero");
        botonSubMenuMeseros.addActionListener(this::botonSubMenuMeserosActionPerformed);

        javax.swing.GroupLayout subMenuMeseroLayout = new javax.swing.GroupLayout(subMenuMesero);
        subMenuMesero.setLayout(subMenuMeseroLayout);
        subMenuMeseroLayout.setHorizontalGroup(
            subMenuMeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subMenuMeseroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonSubMenuMeseros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subMenuMeseroLayout.setVerticalGroup(
            subMenuMeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuMeseroLayout.createSequentialGroup()
                .addComponent(botonSubMenuMeseros)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButton7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton7.setText("Administrar Inventario");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton1.setText("Administracion de Pagos");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton2.setText("Administrar Empleados");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout subMenuAdministradorLayout = new javax.swing.GroupLayout(subMenuAdministrador);
        subMenuAdministrador.setLayout(subMenuAdministradorLayout);
        subMenuAdministradorLayout.setHorizontalGroup(
            subMenuAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subMenuAdministradorLayout.setVerticalGroup(
            subMenuAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuAdministradorLayout.createSequentialGroup()
                .addGroup(subMenuAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
            .addComponent(subMenuAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subMenuMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMenuMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMenuAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        ocultarTodo();
        menu.setVisible(!menu.isVisible());
        controladorMesero.bloquearMesas();
        ocultarSubMenus();
    }//GEN-LAST:event_botonMenuActionPerformed

    private void botonServicioMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonServicioMeseroActionPerformed
        ocultarTodo();
        boolean visible = !servicioMesero.isVisible();
        servicioMesero.setVisible(visible);
        subMenuMesero.setVisible(visible);
        if (visible) {
            servicioOrden.salirDeOrden();
            servicioCuenta.limpiar();
            try {
                controladorMesero.colocarMesas();
            } catch (AccesoALaDataException e) {
                mostrarError(e.getMessage());
            }
        } else {
            controladorMesero.bloquearMesas();
            subMenu.setVisible(visible);
        }
    }//GEN-LAST:event_botonServicioMeseroActionPerformed

    private void botonSubMenuMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubMenuMeserosActionPerformed
        try {
            if (!subMenu.isVisible()) {
                controladorMesero.colocarMeseros();
            } else {
                subMenu.toFront();
            }
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_botonSubMenuMeserosActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        ocultarTodo();
        try {
            controladorInventario.colocarInventario();
            servicioInventario.setVisible(!servicioInventario.isVisible());
            controladorMesero.bloquearMesas();
            if (!servicioInventario.isVisible()) {
                servicioInventario.limpiar();
            }
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdministradorActionPerformed
        ocultarTodo();
        boolean visible = !subMenuAdministrador.isVisible();
        subMenuAdministrador.setVisible(visible);
        controladorMesero.bloquearMesas();
        controladorInventario.limpiarAgregarInsumos();
        limpiarServPagos();
    }//GEN-LAST:event_botonAdministradorActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            controladorInventario.colocarInsumos();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
        boolean visible = !servAdministarInsumos.isVisible();
        servAdministarInsumos.setVisible(visible);
        servicioPagoEmpleado.setVisible(false);
        servDeshabilitarEmpleado.setVisible(false);
        if (!servAdministarInsumos.isVisible()) {
            controladorInventario.limpiarAgregarInsumos();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean visible = !servicioPagoEmpleado.isVisible();
        servAdministarInsumos.setVisible(false);
        servicioPagoEmpleado.setVisible(visible);
        servDeshabilitarEmpleado.setVisible(false);
        limpiarServPagos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean visible = !servDeshabilitarEmpleado.isVisible();
        servAdministarInsumos.setVisible(false);
        servicioPagoEmpleado.setVisible(false);
        servDeshabilitarEmpleado.setVisible(visible);
        try {
            controlParaEmpleado.colocarPersonal();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ocultarTodo();
        boolean visible = !ventanaReporte.isVisible();
        ventanaReporte.setVisible(visible);
        ocultarSubMenus();
        controladorMesero.bloquearMesas();
        try {
            controladorReporte.agregarReportes();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void limpiarServPagos() {
        servicioPagoEmpleado.limpiar();
        servicioPagoEmpleado.limpiarFecha();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdministrador;
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonServicioMesero;
    private javax.swing.JButton botonSubMenuMeseros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel subMenuAdministrador;
    private javax.swing.JPanel subMenuMesero;
    // End of variables declaration//GEN-END:variables
    
    public void cambiarAOrden() {
        boolean visible = cambioDelMesero();
        servicioOrden.setVisible(!visible);
    }
    
    public void cambiarAPago() {
        boolean visible = cambioDelMesero();
        servicioCuenta.setVisible(!visible);
        if (servicioOrden.isVisible()) {
            servicioOrden.setVisible(false);
        }
    }
    
    private boolean cambioDelMesero() {
        boolean visible = !servicioMesero.isVisible();
        subMenuMesero.setVisible(visible);
        servicioMesero.setVisible(visible);
        try {
            controladorMesero.colocarMesas();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
        return visible;
    }
    
    private void ocultarSubMenus() {
        subMenuMesero.setVisible(false);
        subMenuAdministrador.setVisible(false);
    }
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void ocultarTodo() {
        menu.setVisible(false);
        servicioMesero.setVisible(false);
        subMenu.setVisible(false);
        subMenuMesero.setVisible(false);
        subMenuAdministrador.setVisible(false);
        servicioOrden.setVisible(false);
        servicioCuenta.setVisible(false);
        servicioInventario.setVisible(false);
        servAdministarInsumos.setVisible(false);
        servicioPagoEmpleado.setVisible(false);
        servDeshabilitarEmpleado.setVisible(false);
        ventanaReporte.setVisible(false);
        
        servicioInventario.limpiar();
    }
    
}
