/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontent;

import Frontent.Mesero.ServicioMesero;
import Frontent.Mesero.SubMenuMeseros;
import Frontent.Mesero.ServicioPagoCuenta;
import Frontent.Mesero.ServicioDeOrden;
import Backend.Mesero.ControladorMesero;
import Exceptions.AccesoALaDataException;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class JavaBeansCafe extends javax.swing.JFrame {
    
    private final MenuProducto menu;
    private ServicioMesero servicioMesero;
    private ControladorMesero controladorMesero;
    private SubMenuMeseros subMenu;
    private ServicioDeOrden servicioOrden;
    private ServicioPagoCuenta servicioCuenta;
    
    public JavaBeansCafe(MenuProducto menuProductos) {
        initComponents();
        this.menu = menuProductos;
        jDesktopPane1.add(menu);
        ocultarSubMenus();
    }
    
    public void setServicioMesero(ServicioMesero servicioMesero) {
        this.servicioMesero = servicioMesero;
        jDesktopPane1.add(servicioMesero);
    }
    
    public void setSubMenu(SubMenuMeseros subMenu) {
        this.subMenu = subMenu;
        jDesktopPane1.add(subMenu);
    }
    
    public void setControladorMesero(ControladorMesero controladorMesero) {
        this.controladorMesero = controladorMesero;
    }
    
    public void setServicioOrden(ServicioDeOrden servicioOrden) {
        this.servicioOrden = servicioOrden;
        jDesktopPane1.add(servicioOrden);
    }
    
    public void setServicioCuenta(ServicioPagoCuenta servicioCuenta) {
        this.servicioCuenta = servicioCuenta;
        jDesktopPane1.add(servicioCuenta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonMenu = new javax.swing.JButton();
        botonServicioMesero = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        subMenuMesero = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        botonSubMenuMeseros = new javax.swing.JButton();
        subMenuAdministrador = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        jLabel1.setText("JavaBeans Cafe");

        botonMenu.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonMenu.setText("Menu");
        botonMenu.addActionListener(this::botonMenuActionPerformed);

        botonServicioMesero.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonServicioMesero.setText("Servicio de Mesero");
        botonServicioMesero.addActionListener(this::botonServicioMeseroActionPerformed);

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton3.setText("Inventario");

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton4.setText("Servicio de Adminstrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonServicioMesero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenu)
                    .addComponent(botonServicioMesero)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jButton6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton6.setText("Servicio de Adminstrador");

        botonSubMenuMeseros.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        botonSubMenuMeseros.setText("Elegir Mesero");
        botonSubMenuMeseros.addActionListener(this::botonSubMenuMeserosActionPerformed);

        javax.swing.GroupLayout subMenuMeseroLayout = new javax.swing.GroupLayout(subMenuMesero);
        subMenuMesero.setLayout(subMenuMeseroLayout);
        subMenuMeseroLayout.setHorizontalGroup(
            subMenuMeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subMenuMeseroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonSubMenuMeseros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subMenuMeseroLayout.setVerticalGroup(
            subMenuMeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuMeseroLayout.createSequentialGroup()
                .addGroup(subMenuMeseroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(botonSubMenuMeseros))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButton7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButton7.setText("Servicio de Adminstrador");

        javax.swing.GroupLayout subMenuAdministradorLayout = new javax.swing.GroupLayout(subMenuAdministrador);
        subMenuAdministrador.setLayout(subMenuAdministradorLayout);
        subMenuAdministradorLayout.setHorizontalGroup(
            subMenuAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subMenuAdministradorLayout.setVerticalGroup(
            subMenuAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subMenuAdministradorLayout.createSequentialGroup()
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
            .addComponent(subMenuAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subMenuMesero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMenuMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMenuAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuActionPerformed
        menu.setVisible(!menu.isVisible());
        servicioMesero.setVisible(false);
        controladorMesero.bloquearMesas();
        ocultarSubMenus();
    }//GEN-LAST:event_botonMenuActionPerformed

    private void botonServicioMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonServicioMeseroActionPerformed
        boolean visible = !servicioMesero.isVisible();
        servicioMesero.setVisible(visible);
        subMenuMesero.setVisible(visible);
        if (visible) {
            try {
                controladorMesero.colocarMesas();
            } catch (AccesoALaDataException e) {
                mostrarError(e.getMessage());
            }
        }
        if (!visible) {
            servicioOrden.setVisible(visible);
        }
        if (visible) {
            servicioOrden.salirDeOrden();
        }
        menu.setVisible(false);
        subMenuAdministrador.setVisible(false);
        if (!visible) {
            controladorMesero.bloquearMesas();
        }
    }//GEN-LAST:event_botonServicioMeseroActionPerformed

    private void botonSubMenuMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubMenuMeserosActionPerformed
        try {
            controladorMesero.colocarMeseros(!subMenu.isVisible());
            subMenu.toFront();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_botonSubMenuMeserosActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenu;
    private javax.swing.JButton botonServicioMesero;
    private javax.swing.JButton botonSubMenuMeseros;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel subMenuAdministrador;
    private javax.swing.JPanel subMenuMesero;
    // End of variables declaration//GEN-END:variables
    
    public void cambiarAOrden() {
        boolean visible = cambioDelMesero();
        servicioOrden.setVisible(!visible);
    }
    
    public void cambiarAPago() {
        boolean visible = cambioDelMesero();
        servicioCuenta.setVisible(!visible);
        if (servicioOrden.isVisible()) {
            servicioOrden.setVisible(false);
        }
    }
    
    private boolean cambioDelMesero() {
        boolean visible = !servicioMesero.isVisible();
        subMenuMesero.setVisible(visible);
        servicioMesero.setVisible(visible);
        try {
            controladorMesero.colocarMesas();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
        return visible;
    }
    
    private void ocultarSubMenus() {
        subMenuMesero.setVisible(false);
        subMenuAdministrador.setVisible(false);
    }
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
}
