/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontent;

import Modelos.Mesa;

/**
 *
 * @author milton
 */
public class PlantillaMesa extends javax.swing.JPanel {
    
    private final JavaBeansCafe jbcafe;
    private final Mesa mesa;
    
    public PlantillaMesa(JavaBeansCafe jbcafe, Mesa mesa, String mesero, String estado) {
        initComponents();
        this.jbcafe = jbcafe;
        this.mesa = mesa;
        textoEstado.setText("Estado: " + estado);
        textoMesero.setText("Mesero: " + mesero);
        textoCapacidad.setText("Capacidad: " + mesa.getCapacidad());
        botonMesa.setText("Mesa: " + mesa.getNumeroMesa());
    }
    
    public void setOcupado(boolean ocupado) {
        mesa.setEstado(ocupado);
    }
    
    public boolean estaOcupado() {
        return mesa.getEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMesa = new javax.swing.JButton();
        textoEstado = new javax.swing.JLabel();
        textoMesero = new javax.swing.JLabel();
        textoCapacidad = new javax.swing.JLabel();

        botonMesa.setFont(new java.awt.Font("Liberation Sans", 0, 28)); // NOI18N
        botonMesa.setText("Mesa x");
        botonMesa.addActionListener(this::botonMesaActionPerformed);

        textoEstado.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textoEstado.setText("Estado : Ninguno");

        textoMesero.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textoMesero.setText("Mesero : Ninguno");

        textoCapacidad.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        textoCapacidad.setText("Capacidad: x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoMesero)
                    .addComponent(textoEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonMesa)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textoCapacidad)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEstado)
                    .addComponent(botonMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoMesero)
                    .addComponent(textoCapacidad))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMesaActionPerformed
        jbcafe.cambiarAOrden();
    }//GEN-LAST:event_botonMesaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMesa;
    private javax.swing.JLabel textoCapacidad;
    private javax.swing.JLabel textoEstado;
    private javax.swing.JLabel textoMesero;
    // End of variables declaration//GEN-END:variables
    
    public void setEstado(String estado, String mesero) {
        textoEstado.setText("Estado : " + estado);
        textoMesero.setText("Mesero : " + mesero);
    }
    
    public void habilitarBoton(boolean habilitar) {
        botonMesa.setEnabled(habilitar);
    }
    
    public int getNumeroMesa() {
        return mesa.getNumeroMesa();
    }
}
