/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frontent;

import Backend.Mesero.ControladorOrden;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class ServicioDeOrden extends javax.swing.JInternalFrame {
    
    private final JavaBeansCafe jbcafe;
    private ControladorOrden controlador;
    private int numeroOrdenes;
    
    public ServicioDeOrden(JavaBeansCafe jbcafe) {
        initComponents();
        this.jbcafe = jbcafe;
    }
    
    public void setNumeroOrdenes(int numeroOrdenes) {
        this.numeroOrdenes = numeroOrdenes;
    }
    
    public void setControlador(ControladorOrden controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        espacioPedidos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout espacioPedidosLayout = new javax.swing.GroupLayout(espacioPedidos);
        espacioPedidos.setLayout(espacioPedidosLayout);
        espacioPedidosLayout.setHorizontalGroup(
            espacioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        espacioPedidosLayout.setVerticalGroup(
            espacioPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(espacioPedidos);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel2.setText("Selecciona los Productos del Cliente");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel3.setText("Opciones del menu");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel4.setText("Productos Seleccionados");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jbcafe.cambiarAOrden();
        controlador.reiniciarInsumos();
        setNumeroOrdenes(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioPedidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    
    
    public void setCuadricula(int filas) {
        jPanel1.setLayout(new GridLayout(filas, 1, 5, 5));
    }
    
    public void agregarProducto(OpcionMenu opcionMenu) {
        jPanel1.add(opcionMenu);
    }
    
    public void limpiarMenu() {
        jPanel1.removeAll();
    }
    
    public void mostrar(boolean mostrar) {
        this.setVisible(mostrar);
    }
    
    public void agregarPedido(PlantillaOrden plantilla) {
        numeroOrdenes++;
        espacioPedidos.setLayout(new GridLayout(numeroOrdenes, 1, 5, 5));
        espacioPedidos.add(plantilla);
        actualizar();
    }
    
    public void eliminarOrden(PlantillaOrden plantilla) {
        numeroOrdenes--;
        espacioPedidos.remove(plantilla);
        espacioPedidos.setLayout(new GridLayout(numeroOrdenes, 1, 5, 5));
        actualizar();
    }
    
    public void limpiarPedido() {
        espacioPedidos.removeAll();
    }
    
    public void actualizar() {
        espacioPedidos.revalidate();
        espacioPedidos.repaint();
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
}
