/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frontent.Administrador;

import Backend.Administrador.ControladorPagoEmpleado;
import Exceptions.AccesoALaDataException;
import Exceptions.ErrorIngresarDatosException;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class ServicioPagoEmpleado extends javax.swing.JInternalFrame {
    
    private ControladorPagoEmpleado controladorPago;
    
    public ServicioPagoEmpleado() {
        initComponents();
    }

    public void setControladorPago(ControladorPagoEmpleado controladorPago) {
        this.controladorPago = controladorPago;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioDia = new javax.swing.JTextField();
        espacioMes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        espacioAño = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonModificarFecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        espacioDia.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        espacioMes.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel1.setText("Edita la fecha");

        espacioAño.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel2.setText("dia");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel3.setText("mes");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel4.setText("año");

        botonModificarFecha.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        botonModificarFecha.setText("Modificar Fecha y Generar Pagos");
        botonModificarFecha.addActionListener(this::botonModificarFechaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel5.setText("Elige un Empleado para registrar su pago");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jButton1.setText("Buscar Pagos de la Fecha");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(espacioDia, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(espacioMes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(espacioAño, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botonModificarFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacioMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espacioAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addComponent(botonModificarFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(164, 164, 164))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarFechaActionPerformed
        try {
            controladorPago.generarRegistrosPago(getDia(), getMes(), getAño());
        } catch (AccesoALaDataException | ErrorIngresarDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_botonModificarFechaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controladorPago.buscarPagosPorFecha();
        } catch (AccesoALaDataException | ErrorIngresarDatosException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarFecha;
    private javax.swing.JTextField espacioAño;
    private javax.swing.JTextField espacioDia;
    private javax.swing.JTextField espacioMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void setFilas(int filas) {
        jPanel1.setLayout(new GridLayout(filas, 1, 5, 5));
    }
    
    public void agregarEmpleado(PlantillaEmpleado plantillaEmpleado) {
        jPanel1.add(plantillaEmpleado);
        actualizar();
    }
    
    public void eliminarEmpleado(PlantillaEmpleado plantillaEmpleado) {
        jPanel1.remove(plantillaEmpleado);
        actualizar();
    }
    
    public void agregarInformacion(String mensaje) {
        setFilas(1);
        JLabel informacion = new JLabel(mensaje);
        informacion.setFont(new java.awt.Font("Liberation Sans", 0, 24));
        jPanel1.add(informacion);
        actualizar();
    }
    
    private void actualizar() {
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public void limpiar() {
        jPanel1.removeAll();
    }
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public String getDia() {
        return espacioDia.getText();
    }
    
    public String getMes() {
        return espacioMes.getText();
    }
    
    public String getAño() {
        return espacioAño.getText();
    }
    
    public void limpiarFecha() {
        espacioDia.setText("");
        espacioMes.setText("");
        espacioAño.setText("");
    }
    
}
