/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frontent.Mesero;

import Backend.Mesero.ControladorOrden;
import Modelos.ProductoMenu;

/**
 *
 * @author milton
 */
public class PlantillaOrden extends javax.swing.JPanel {
    
    private final ControladorOrden controladorOrden;
    private final ProductoMenu producto;
    private int cantidad;
    
    public PlantillaOrden(ControladorOrden controladorOrden, ProductoMenu producto, int cantidad) {
        initComponents();
        this.controladorOrden = controladorOrden;
        this.producto = producto;
        this.espacioNombre.setText(producto.getNombre());
        this.cantidad = cantidad;
    }
    
    public int getCodigo() {
        return producto.getCodigo();
    }
    
    public int getCantidad() {
        return cantidad;
    }
    
    public void agregarUnidad(int elemento) {
        cantidad += elemento;
        espacioCantidad.setText("Cantidad: " + cantidad);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioNombre = new javax.swing.JLabel();
        espacioCantidad = new javax.swing.JLabel();
        botonReducir = new javax.swing.JButton();

        espacioNombre.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        espacioNombre.setText("Nombre Producto");

        espacioCantidad.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        espacioCantidad.setText("Cantidad: 1");

        botonReducir.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        botonReducir.setText("Reducir en 1");
        botonReducir.addActionListener(this::botonReducirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(espacioNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(espacioCantidad))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonReducir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacioNombre)
                    .addComponent(espacioCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonReducir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonReducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReducirActionPerformed
        controladorOrden.revertirPedido(this, producto);
    }//GEN-LAST:event_botonReducirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonReducir;
    private javax.swing.JLabel espacioCantidad;
    private javax.swing.JLabel espacioNombre;
    // End of variables declaration//GEN-END:variables
}
