/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Frontent.Mesero;

import Backend.Mesero.ControladorPago;
import Exceptions.AccesoALaDataException;
import Frontent.JavaBeansCafe;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author milton
 */
public class ServicioPagoCuenta extends javax.swing.JInternalFrame {
    
    private final JavaBeansCafe jbcafe;
    private ControladorPago controlador;
    
    public ServicioPagoCuenta(JavaBeansCafe jbcafe) {
        initComponents();
        this.jbcafe = jbcafe;
    }
    
    public void setControladorPago(ControladorPago controlador) {
        this.controlador = controlador;
    }
    
    public void setTotal(double total) {
        espacioTotal.setText("Total: " + total);
    }
    
    public void setDetallesMesa(int numeroMesa, String horaOcupacion) {
        detallesMesa.setText("Mesa No. " + numeroMesa + " | Hora de Ocupacion: " + horaOcupacion);
    }
    
    public String getPropina() {
        return espacioPropina.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        espacioPropina = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        espacioTotal = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        detallesMesa = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel1.setText("Pago de Cuenta");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel2.setText("Detalles de Cuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        jLabel3.setText("Agregar Propina");

        espacioPropina.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        jButton1.setText("Pagar Cuenta");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        espacioTotal.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        espacioTotal.setText("Total: 000");

        botonRegresar.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(this::botonRegresarActionPerformed);

        detallesMesa.setFont(new java.awt.Font("Liberation Sans", 0, 25)); // NOI18N
        detallesMesa.setText("Mesa x Ocupada a las");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonRegresar)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(446, 446, 446))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(espacioPropina, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(espacioTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(detallesMesa)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRegresar)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detallesMesa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(espacioPropina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(espacioTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            controlador.pagarCuenta(espacioPropina.getText());
            jbcafe.cambiarAPago();
        } catch (AccesoALaDataException e) {
            mostrarError(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        jbcafe.cambiarAPago();
        controlador.eliminarPedidoMesero();
        limpiar();
    }//GEN-LAST:event_botonRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JLabel detallesMesa;
    private javax.swing.JTextField espacioPropina;
    private javax.swing.JLabel espacioTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void setNumeroDetalles(int numeroDetalles) {
        jPanel1.setLayout(new GridLayout(numeroDetalles * 3, 1, 5, 5));
    }
    
    public void agregarDetalle(String producto, double precio, int cantidad, double subTotal) {
        JLabel detalle1 = new JLabel("Producto: " + producto + ", Precio: Q" + precio);
        detalle1.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        jPanel1.add(detalle1);
        JLabel detalle2 = new JLabel("Cantidad: " + cantidad + ", Sub Total: Q" + subTotal);
        detalle2.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        jPanel1.add(detalle2);
        JLabel espacio = new JLabel();
        espacio.setFont(new java.awt.Font("Liberation Sans", 0, 20));
        jPanel1.add(espacio);
    }
    
    public void limpiar() {
        jPanel1.removeAll();
    }
    
    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }
}
